services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_commerce_db
    ports:
      - "3306:3306"
    networks:
      - case_network
    volumes:
      - mysql_data:/var/lib/
  
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: always
    environment:
      CB_SERVER_PASSWORD: admin
    ports:
      - "85:8978"
    depends_on:
      - mysql
    networks:
      - case_network

networks:
  case_network:
    driver: bridge

volumes:
  mysql_data:
